const mockBooks = [
	{
		title: "Clean Code",
		author: "Robert C. Martin",
		pages: 464,
		status: "in progress",
		pagesRead: 200,
		category: "Programming",
		cover: "https://cdn4.libris.ro/img/pozeprod/11033/11032978-1.jpg",
	},

	{
		title: "Eloquent JavaScript",
		author: "Marijn Haverbeke",
		pages: 472,
		status: "queue",
		pagesRead: 0,
		category: "JavaScript",
		cover: "https://m.media-amazon.com/images/I/81HqVRRwp3L.jpg",
	},

	{
		title: "Design Patterns",
		author: "Erich Gamma",
		pages: 416,
		status: "finished",
		pagesRead: 416,
		category: "Software Development",
		cover: "https://m.media-amazon.com/images/I/71sjeQGh7VL._AC_UF1000,1000_QL80_.jpg",
	},
	{
		title: "Sapiens: A Brief History of Humankind",
		author: "Yuval Noah Harari",
		pages: 464,
		status: "queue",
		pagesRead: 0,
		category: "History",
		cover: "https://cdn.dc5.ro/img-prod/1326017767-0.jpeg",
	},
	{
		title: "Atomic Habits",
		author: "James Clear",
		pages: 320,
		status: "in progress",
		pagesRead: 120,
		category: "Self-Development",
		cover: "https://m.media-amazon.com/images/I/81ANaVZk5LL.jpg",
	},
	{
		title: "Dune",
		author: "Frank Herbert",
		pages: 688,
		status: "queue",
		pagesRead: 0,
		category: "Science Fiction",
		cover: "https://i.pinimg.com/736x/3f/37/fb/3f37fbc161a83e952dfc8f5103f36939.jpg",
	},
	{
		title: "The Hobbit",
		author: "J.R.R. Tolkien",
		pages: 310,
		status: "finished",
		pagesRead: 310,
		category: "Fantasy",
		cover: "https://m.media-amazon.com/images/I/712cDO7d73L.jpg",
	},
	{
		title: "To Kill a Mockingbird",
		author: "Harper Lee",
		pages: 336,
		status: "finished",
		pagesRead: 336,
		category: "Classic",
		cover: "https://media.glamour.com/photos/56e1f3c462b398fa64cbd304/master/w_1600%2Cc_limit/entertainment-2016-02-18-main.jpg",
	},
	{
		title: "1984",
		author: "George Orwell",
		pages: 328,
		status: "in progress",
		pagesRead: 150,
		category: "Dystopian",
		cover: "https://i.etsystatic.com/31513412/r/il/455f92/4081428546/il_fullxfull.4081428546_dl25.jpg",
	},
	{
		title: "The Subtle Art of Not Giving a F*ck",
		author: "Mark Manson",
		pages: 224,
		status: "finished",
		pagesRead: 224,
		category: "Self-Help",
		cover: "https://m.media-amazon.com/images/I/71QKQ9mwV7L.jpg",
	},
];

export default mockBooks;
